In [1]:
#EXERCICE 1 

In [3]:
for i in range (2000,3001):
    if i%7==0 and i%5!=0:
        print (i)

2002
2009
2016
2023
2037
2044
2051
2058
2072
2079
2086
2093
2107
2114
2121
2128
2142
2149
2156
2163
2177
2184
2191
2198
2212
2219
2226
2233
2247
2254
2261
2268
2282
2289
2296
2303
2317
2324
2331
2338
2352
2359
2366
2373
2387
2394
2401
2408
2422
2429
2436
2443
2457
2464
2471
2478
2492
2499
2506
2513
2527
2534
2541
2548
2562
2569
2576
2583
2597
2604
2611
2618
2632
2639
2646
2653
2667
2674
2681
2688
2702
2709
2716
2723
2737
2744
2751
2758
2772
2779
2786
2793
2807
2814
2821
2828
2842
2849
2856
2863
2877
2884
2891
2898
2912
2919
2926
2933
2947
2954
2961
2968
2982
2989
2996


In [26]:
#EXERCICE 2

In [27]:
def factorial(x):
    f=1
    for i in range(1,x+1):
        f=f*i
        
    return f

In [28]:
factorial(5)

120

In [29]:
factorial(10)

3628800

In [39]:
#EXERCICE 3

In [2]:
number = int(input("Type a number: "))

dico = {}
for i in range(1, number+1):
    dico[i] = i*i

print(dico)

Type a number: 7
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49}


In [4]:
#EXERCICE 4

In [1]:
def removechar(str,n):
    part1=str[:n]
    part2=str[n+1]
    return part1+part2

In [3]:
removechar("gomycode",5)

'gomycd'

In [4]:
#EXERCICE 5

In [5]:
import numpy as np

In [10]:
arr= np.arange(10).reshape(5, 2)

In [11]:
print(arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [12]:
(arr.tolist())

[[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]]

In [13]:
#EXERCICE 6

In [20]:
A = np.array([0, 1, 2])

In [21]:
print(A)

[0 1 2]


In [22]:
B = np.array([2, 1 , 0])

In [23]:
print(B)

[2 1 0]


In [24]:
print(np.cov(A, B))

[[ 1. -1.]
 [-1.  1.]]


In [25]:
#EXERCICE 7

In [28]:
def Q(d):
    c = 50
    h = 30
    result = ((1.0)*(2 * c * d)/h)**(0.5)
    return str(int(result))

input_nums = input("numbers:")
result = []
for num in input_nums.split(','):
    int_num = int(num)
    temp = Q(int_num)
    result.append(temp)

print(','.join(result))

numbers:8
5
